name: flutter_infinite_list
description: FilmView App

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^3.2.0
  http: ^0.12.0
  equatable: ^1.0.0
  tuple: ^1.0.3
  badges: ^1.1.1
  transparent_image: ^1.0.0
  cached_network_image: ^2.0.0
  data_connection_checker: ^0.3.4
  get_it: ^4.0.2

flutter:
  uses-material-design: true
